name: CI

on:
  workflow_dispatch:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.0

      - name: Run automatic tests
        run: go test -cover ./...

      - name: Run Style.yml
        run: test -z
      
      - name: Run Style function
        run: go fmt
